version: "3"
services:
  rm:
    build: ./docker/
    volumes:
      - ./:/app
    healthcheck:
      test: ls /app/output/*.zip 1> /dev/null 2>&1 || exit 1
      interval: 1m
      timeout: 10s
      retries: 3