find_package(Protobuf REQUIRED)

protobuf_generate_cpp(PROTO_SOURCES PROTO_HEADERS ${CMAKE_SOURCE_DIR}/src/Mumble.proto)

add_custom_target(protobuf_autogenerated_code DEPENDS ${PROTO_SOURCES} ${PROTO_HEADERS})
